<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Create Programador' => 'Agregar Programador',
    'Created At' => 'Creado',
    'Delete' => 'Borrar',
    'Dni' => 'Cedula',
    'Email' => 'Correo Eléctronico',
    'ID' => '',
    'Languages' => 'Lenguajes',
    'Last Name' => 'Apellidos',
    'Name' => 'Nombres',
    'Programadors' => 'Programadores',
    'Save' => 'Guardar',
    'The requested page does not exist.' => '',
    'Update' => 'Actualizar',
    'Update Programador: {name}' => 'Actualizando a: {name}',
    'Actualizado' => '',
];
